version: '2'
services:
  server:
    image: oswynb/ideal-pancake
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
